---
kind: pipeline
name: home
type: docker
environment:
  publish_image_tag: "2021.05.24.1"
steps:
  - name: build
    image: maven:3-jdk-8
    commands:
      - mvn install -Dmaven.test.skip=true
    volumes:
      - name: mvn-config
        path: /root/.m2
      - name: mvn-repo
        path: /usr/local/java/apache-maven-3.6.1/repo
  - name: docker-build-push
    image: plugins/docker
    settings:
      registry: 192.168.8.13
      repo: 192.168.8.13/library/tomcat8
      username: admin
      password: Ycl123456ycl
      use_cache: true
      insecure: true
      tags:
        - "${publish_image_tag}"
      volumes:
        - name: docker
          path: /var/run/docker.sock
  - name: ssh-deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.8.11
      username: root
      password: ycl123456ycl
      port: 22
      script:
        - echo hello
        - echo 'drone' > /root/drone.txt
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: 02510750b5c335346de2a5d67d4a0e65bbf0163c49c094970c37de10a00720cc
      type: markdown
volumes:
  - name: mvn-config
    host:
      path: /usr/local/java/apache-maven-3.6.1/conf
  - name: mvn-repo
    host:
      path: /usr/local/java/apache-maven-3.6.1/repo
  - name: docker
    host:
      path: /var/run/docker.sock



