kind: pipeline
name: default
type: docker
steps:
  - name: test
    image: maven:3-jdk-10
    network_mode: host
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
